name: Download Habbo Files

env:
  FILE_PATH: src/habbo/index.js

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i

      # Download assets
      - name: Download Badges
        run: node $FILE_PATH -c badges -o origins -origins

      - name: Download Furnitures
        run: node $FILE_PATH -c furnitures -o origins -origins

      - name: Download Gamedata Files
        run: node $FILE_PATH -c gamedata -o origins -origins

      # Commit
      - uses: EndBug/add-and-commit@v9
        with:
          message: New changes detected
          default_author: user_info
          author_name: Hab Track
          committer_name: habbo-downloader
